global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'siem-api'
    static_configs:
      - targets: ['api:8000']
  
  - job_name: 'opensearch'
    static_configs:
      - targets: ['opensearch:9200']
